#!/bin/bash
set -eu

while [[ $# -gt 0 ]]; do
    key="$1"
    case ${key} in
        --dea-module )          shift
                                MODULE=$1
                                ;;
        --queue )               shift
                                QUEUE=$1
                                ;;
        --project )             shift
                                PROJECT=$1
                                ;;
        --timerange )           shift
                                RANGE_EXP=$1
                                ;;
        * )                     exit 0
    esac
    shift
done

WORKDIR=/g/data/v10/work/coherence/$(date '+%F')
SUBMISSION_LOG="$WORKDIR"/Coherence_$(date '+%H_%m_%s').log

mkdir -p "${WORKDIR}"
echo "Start time: " "$(date '+%F-%T')" > "$SUBMISSION_LOG"

module use /g/data/v10/public/modules/modulefiles
module load "${MODULE}"

cd "${WORKDIR}"

nohup "$SHELL" > "$SUBMISSION_LOG" 2>&1 << EOF &
echo "Logging into: ${SUBMISSION_LOG}"
echo ""
echo Loading module "${MODULE}"
echo ""

# Check if we can connect to the database
datacube -vv system check

echo ""
echo "Starting coherence process......"
##################################################################################################
# Qsub dea-coherence process
##################################################################################################
qsub -V -N dea-coherence -q "${QUEUE}" -W umask=33 -l wd,walltime=10:00:00,mem=25GB,ncpus=1 -P "${PROJECT}" \
    -o "$WORKDIR" -e "$WORKDIR" -m abe -M nci.monitor@dea.ga.gov.au \
    -- dea-coherence --check-siblings --check-locationless --check-downstream-ds "${RANGE_EXP}"

EOF
