dist: trusty
# tests primarily focused on lambda component
language: python
python:
  - "3.6"
sudo: false
addons:
  apt:
    packages:
      - shellcheck

env:
  global:
    - DEA_ENVIRONMENT='test'

git:
  depth: 99999


cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -r requirements.txt

script:
  - npm install -g serverless
  - pushd lambda_functions/execute_ssh_command_js && serverless plugin install --name serverless-pseudo-parameters && popd
  - ./scripts/check-code.sh

before_deploy:
  - cd lambda_functions/execute_ssh_command_js/ && npm install
  - npm --version
  # Configure serverless AWS custom profile settings.
  # AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_DEFAULT_REGION are expected to be
  # configured in travis project web settings
  - serverless config credentials --provider aws --key $aws_access_key_id --secret $aws_secret_access_key --profile prodProfile --overwrite

deploy:
 -  provider: script
    script:
      # Serverless deploy to production environment after merging to production branch
      - sls deploy -v -s prod
    skip_cleanup: true # Don't re-run the tests
    on:
        branch: production

after_deploy:
  # Update the code on the NCI
  - sls invoke -f git_pull_prod -l -s prod
