dist: xenial
language: python

python:
  - "3.7"

sudo: false

env:
  global:
    - DEA_ENVIRONMENT='test'

git:
  depth: 99999

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -r requirements.txt

script:
  - npm install -g serverless
  # Configure serverless AWS custom profile settings.
  # AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_DEFAULT_REGION are expected to be
  # configured in travis project web settings
  - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --profile prodProfile --overwrite
  - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --profile dea-prod --overwrite
  - ./scripts/check-code.sh

after_success:
  - codecov

before_deploy:
  - npm --version

deploy:
 # Serverless deploy to production environment after merging to production branch
 - provider: script
   script:
     - cd "$PWD"/lambda_functions/execute_ssh_command_js && npm install
     - sls deploy -v -s prod
   skip_cleanup: true  # Don't re-run the tests
   on:
      branch: production
