---
dist: trusty
# tests primarily focused on lambda component
language: python
python:
  - "3.6"
sudo: false
addons:
  apt:
    packages:
      - shellcheck

env:
  global:
    - DEA_ENVIRONMENT='test'

git:
  depth: 99999


cache:
  directories:
    - $HOME/.cache/pip

install:
  - python3 -m pip install -r requirements.txt
  - ./scripts/install_script all

script:
  - ./scripts/check-code.sh
