dist: bionic
language: python

python:
  - "3.7"

before_install:
  - pip install -r requirements.txt
  - npm install -g serverless

script:
  # Configure custom AWS profiles using serverless
  # AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_DEFAULT_REGION are expected to be
  # configured in travis project web settings.
  - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --profile prodProfile --overwrite
  - aws sts get-caller-identity
  - ./scripts/check-code.sh

after_success:
  - codecov

deploy:
 # Serverless deploy to Production environment every time from master
 - provider: script
   script: ./scripts/deploy.sh
   skip_cleanup: true  # Don't re-run the tests
   on:
      branch: master
      repo: GeoscienceAustralia/dea-orchestration
