#!/bin/bash
set -eu

while [[ "$#" -gt 0 ]]; do
    key="$1"
    case "${key}" in
        --dea-module )          shift
                                MODULE="$1"
                                ;;
        --queue )               shift
                                QUEUE="$1"
                                ;;
        --project )             shift
                                PROJECT="$1"
                                ;;
        --min-trash-age )       shift
                                TRASH_AGE="$1"
                                ;;
        --search-paths )        shift
                                SEARCH_PATHS="$*"
                                break # Last input argument and hence exiting while loop
                                ;;
        * )
          echo "Input key, '$key', did not match the expected input argument key"
          exit 1
          ;;
    esac
    shift
done

WORKDIR=/g/data/v10/work/archive/clean/$(date '+%Y-%m')
SUBMISSION_LOG="$WORKDIR"/dea-clean_$(date '+%F_%T').log

mkdir -p "${WORKDIR}"
echo "Start time: " "$(date '+%F-%T')" > "$SUBMISSION_LOG"

module use /g/data/v10/public/modules/modulefiles
module load "${MODULE}"

MIN_TRASH_AGE="--min-trash-age-hours ${TRASH_AGE}"

cd "${WORKDIR}"

echo Submitting PBS job to run dea-clean archived "${MIN_TRASH_AGE}" "${SEARCH_PATHS}"

nohup "$SHELL" > "$SUBMISSION_LOG" 2>&1 << EOF &
echo "Logging into: ${SUBMISSION_LOG}"
echo ""
echo Loading module ${MODULE}
echo ""

# Check if we can connect to the database
datacube -vv system check

echo ""
echo "Starting dea-clean process......"

##################################################################################################
# Qsub dea-clean process
##################################################################################################
qsub -V -N dea-clean -q ${QUEUE} -W umask=33 -l wd,walltime=20:00:00,mem=25GB,ncpus=1 -P ${PROJECT} \
-o ${WORKDIR} -e ${WORKDIR} -m abe -M nci.monitor@dea.ga.gov.au \
-- dea-clean archived --dry-run ${MIN_TRASH_AGE} ${SEARCH_PATHS}

EOF
