# Monitor Digital Earth Australia processes running at the NCI
#
# Sequence of steps before and after sls deploy:
#
#  1) Create the SQS queue within your service (if sqs queue does not exist)
#  2) Add permissions on the SQS queue to allow S3 to publish notifications
#      https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-configure-lambda-function-trigger.html
#      https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-basic-architecture.html
#  3) Enable and attach event notifications for the desired S3 Bucket to SQS queue
#  4) npm install
#  5) sls deploy --aws-profile <Existing AWS Profile Name> -vv -s prod

service: s3stat-download

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
custom:
  pythonRequirements:
    dockerizePip: non-linux
  Stage: ${opt:stage, self:provider.stage}
  profile:
    dev: dea-data-dev

package:
  exclude:
    - node_modules/**
    - .idea/**
    - .requirements/**
    - env/**
    - README.md
    - package.json
    - package-lock.json
    - requirements.txt


provider:
  name: aws
  runtime: python3.7
  timeout: 60  # 60 seconds. Default is 6 seconds
  memorySize: 512  # in MB, default is 1024
  stage: dev
  # Since SES is not supported in Sydney region, all emails are pushed to the
  # S3 bucket in us-west-2 region. For s3 to trigger SQS and SQS trigger lambda function execution, all the aws
  # resources need to be in the same region as S3 bucket.
  region: ap-southeast-2
  deploymentBucket: "s3stat-monitoring"
  profile: ${self:custom.profile.${opt:stage}}
  tags:
    repo: https://github.com/GeoscienceAustralia/dea-data
    author: nci.monitor@dea.ga.gov.au
    purpose: s3-download-automation
  iamRoleStatements:
  - Effect: 'Allow'
    Action:
      - 'ssm:GetParameter'
      - 'ssm:GetParameters'
      - 'ssm:DescribeParameters'
    Resource:
      - "arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/orchestrator.*"
  - Effect: 'Allow'
    Action: 'kms:Decrypt'
    Resource:
      - "arn:aws:kms:#{AWS::Region}:#{AWS::AccountId}:key/*"
  - Effect: "Allow"
    Action:
      - "*"
    Resource: "arn:aws:s3:::s3stat-monitoring/*"

  # Service wide environment variables declaration
  environment:
    SSM_USER_PATH: 's3stat.monitoring'

functions:
  s3stat-monitor:
    handler: s3_monitoring.handler.handler
    description: Download data from s3stat page 
    events:
      - schedule: rate(23 hours)

