# Welcome to Serverless!
#
# This file is the main config file for your service.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!
service: testing

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

# plugins:
plugins:
  # install serverless pseudo parameters using the following:
  #   1) $ npm install serverless-pseudo-parameters --save-dev
  - serverless-pseudo-parameters

custom:
  Stage: ${opt:stage, self:provider.stage}
  profiles:
    dev: devProfile
  CustEnv:
    s3Bucket:
      dev: "dea-lambdas-dev"

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 300 # 5 minutes (max). Default is 6 seconds
  profile: ${self:custom.profiles.${self:custom.Stage}}
  environment:
    hostkey: 'orchestrator.raijin.users.default.host'
    userkey: 'orchestrator.raijin.users.default.user'
    pkey: 'orchestrator.raijin.users.default.pkey'
    DEA_MODULE: dea/20180705
    PROJECT: v10
    QUEUE: express
    YEAR: 2018
  region: ap-southeast-2
  deploymentBucket: ${self:custom.CustEnv.s3Bucket.${self:custom.Stage}}
  stackTags:
    repo: dea-orchestration
    author: santosh.mohan@ga.gov.au
    purpose: dea-env-automation-testing
# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ssm:GetParameters'
        - 'ssm:DescribeParameters'
      Resource:
        - "arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/orchestrator.*"
        - "arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/pipeline.*"
    - Effect: 'Allow'
      Action: 'kms:Decrypt'
      Resource:
        - "arn:aws:kms:#{AWS::Region}:#{AWS::AccountId}:key/*"

functions:
  test_deaenv_sync:
    handler: handler.execute_ssh_command
    environment:
      cmd: 'test_deaenv_sync --deamodule <%= deamodule %>
                             --year <%= year %>
                             --queue <%= queue %>
                             --project <%= project %>'
    events:
      - schedule:
          rate: cron(15 08 * * ? *) # Run daily, at 08:15:00 am UTC time
          enabled: false
          input:
            deamodule: ${self:provider.environment.DEA_MODULE}
            year: ${self:provider.environment.YEAR}
            queue: ${self:provider.environment.QUEUE}
            project: ${self:provider.environment.PROJECT}
  test_deaenv_index_ingest:
    handler: handler.execute_ssh_command
    environment:
      cmd: 'test_deaenv_index_ingest --deamodule <%= deamodule %>
                                     --year <%= year %>'
    events:
      - schedule:
          rate: cron(00 11 * * ? *) # Run daily, at 11:00:00 am UTC time
          enabled: false
          input:
            deamodule: ${self:provider.environment.DEA_MODULE}
            year: ${self:provider.environment.YEAR}
  test_deaenv_nbconvert:
    handler: handler.execute_ssh_command
    environment:
      cmd: 'test_deaenv_nbconvert --deamodule <%= deamodule %>'
    events:
      - schedule:
          rate: cron(00 14 * * ? *) # Run daily, at 02:00:00 pm UTC time
          enabled: false
          input:
            deamodule: ${self:provider.environment.DEA_MODULE}
  test_deaenv_fc:
    handler: handler.execute_ssh_command
    environment:
      cmd: 'test_deaenv_fc --deamodule <%= deamodule %>
                           --year <%= year %>
                           --queue <%= queue %>
                           --tag <%= tag %>
                           --project <%= project %>'
    events:
      - schedule:
          rate: cron(00 15 * * ? *) # Run daily, at 03:00:00 pm UTC time
          enabled: false
          input:
            deamodule: ${self:provider.environment.DEA_MODULE}
            year: ${self:provider.environment.YEAR}
            queue: ${self:provider.environment.QUEUE}
            project: ${self:provider.environment.PROJECT}
            tag: ${self:provider.environment.YEAR}
  test_deaenv_stats:
    handler: handler.execute_ssh_command
    environment:
      cmd: 'test_deaenv_stats --deamodule <%= deamodule %>
                              --queue <%= queue %>
                              --project <%= project %>'
    events:
      - schedule:
          rate: cron(00 18 * * ? *) # Run daily, at 06:00:00 pm UTC time
          enabled: false
          input:
            deamodule: ${self:provider.environment.DEA_MODULE}
            queue: ${self:provider.environment.QUEUE}
            project: ${self:provider.environment.PROJECT}