#!/bin/bash
set -eu

while [[ $# -gt 0 ]]; do
    key="$1"
    case ${key} in
        --year )                shift
                                YEAR=$1
                                ;;
        --product )             shift
                                PRODUCT=$1
                                ;;
        --dea-module )          shift
                                DEA_MODULE=$1
                                ;;
        --queue )               shift
                                QUEUE=$1
                                ;;
        --stage )               shift
                                STAGE=$1
                                ;;
        --project )             shift
                                PROJECT=$1
                                ;;
        * )                     exit 1
    esac
    shift
done

WORKDIR=/g/data/v10/work/ingest/"${PRODUCT}"/$(date '+%FT%H%M')
SUBMISSION_LOG="${WORKDIR}"/ingest-submission-${PRODUCT}-$(date '+%F-%T').log
JOB_NAME="${YEAR}_${PRODUCT}"
count=0
dbhostname='agdcdev-db.nci.org.au'
dbport='6432'
dbname='datacube'

mkdir -p "${WORKDIR}"
echo "Start time: " "$(date '+%F-%T')" > "$SUBMISSION_LOG"

# Launch the submission in the background, outputting results to a log file
cd "${WORKDIR}"
nohup "$SHELL" > "$SUBMISSION_LOG" 2>&1 <<EOF &

echo "Logging job: ${JOB_NAME} into: ${SUBMISSION_LOG}"

echo ""
echo Loading module "${DEA_MODULE}"
module use /g/data/v10/public/modules/modulefiles
module load "${DEA_MODULE}"
echo ""

# Check if we can connect to the database
datacube -vv system check

# Read agdc datasets from the database before ingest process
echo ""
echo "**********************************************************************"
while read -r LINE; do
  if [[ "$count" -eq 1 ]]
  then
      IFS=': '
      set ${LINE}
      echo "Connected to the database hostname: $2"
      dbhostname="$2"
      count=$((count+1))
  elif [[ "$count" -eq 2 ]]
  then
      IFS=': '
      set $LINE
      echo "Connected to the database port number: $2"
      dbport="$2"
      count=$((count+1))
  elif [[ "$count" -eq 3 ]]
  then
      IFS=': '
      set $LINE
      echo "Connected to the database name: $2"
      dbname="$2"
      count=$((count+1))
  fi

  if [[ "${STAGE}" == "dev"  && "$LINE" == "[dea-dev]" ]]; then
      count=$((count+1))
  fi

  if [[ "${STAGE}" == "prod"  && "$LINE" == "[datacube]" ]]; then
      count=$((count+1))
  fi
done  < "$DATACUBE_CONFIG_PATH"

echo "Read previous agdc_dataset product names and count before ingest process"
psql -h "${dbhostname}" -p "${dbport}"  -d "${dbname}"  -c 'select name, count(*) FROM agdc.dataset a, agdc.dataset_type b where a.dataset_type_ref = b.id group by b.name'
echo "**********************************************************************"

echo ""
echo "Executing ingest for ${YEAR} ${PRODUCT}"
yes Y | dea-submit-ingest qsub --project "${PROJECT}" --queue "${QUEUE}" -n 5 -t 10 --name "${JOB_NAME}" "${PRODUCT}" "${YEAR}"
EOF