#!/bin/bash

set -eu


while [[ $# -gt 0 ]]; do
    key="$1"
    case ${key} in
        --year )                shift
                                YEAR=$1
                                ;;
        --app-config-file )     shift
                                APP_CONFIG_FILE=$1
                                ;;
        --dea-module )          shift
                                DEA_MODULE=$1
                                ;;
        --queue )               shift
                                QUEUE=$1
                                ;;
        --project )             shift
                                PROJECT=$1
                                ;;
        * )                     exit 1
    esac
    shift
done


echo Executing stacker for "${YEAR}" "${APP_CONFIG_FILE}"
echo Loading module "${DEA_MODULE}"

module use /g/data/v10/public/modules/modulefiles
module use /g/data/v10/private/modules/modulefiles

module load "${DEA_MODULE}"

dea-stacker submit -v -v --project "${PROJECT}" --queue "${QUEUE}" --year "${YEAR}" --app-config "${APP_CONFIG_FILE}"
