#!/bin/bash

set -eu

while [[ $# -gt 0 ]]; do
    key="$1"
    case ${key} in
        --deamodule )           shift
                                MODULE=$1
                                ;;
        * )                     exit 0
    esac
    shift
done

WORKDIR=/g/data/v10/work/dea_env_test
SUBMISSION_LOG="$WORKDIR"/log_files/test_deaenv_index_ingest-$(date '+%F-%T').log
CONFIGFILE="$(pwd)"/datacube_config.conf

# Copy yaml files from repo
sh dea_testscripts/cp_indingest_yaml_files.sh "$WORKDIR"

# Check if output directory exists, else create one
[ -d "$WORKDIR/output_files/idx_ingest" ] || mkdir -p "$WORKDIR"/output_files/idx_ingest
mkdir -p "$WORKDIR/log_files"
echo "Start time: " $(date '+%F-%T') > "$SUBMISSION_LOG"

# Get database name from the config file
configname=""
databasename=""
while IFS=': ' read -r a b; do
    if [[ "$a" == "["* ]]; then
       configname=$a
    fi

    if [[ "$a" == "db_database" && "$configname" == "[datacube]" ]]; then
       databasename="$b"
    fi
done < "$CONFIGFILE"
dcdb="datacube"

nohup "$SHELL" > "$SUBMISSION_LOG" 2>&1 << EOF &
echo "Logging results into: ${SUBMISSION_LOG}"
module use /g/data/v10/public/modules/modulefiles
module load "${MODULE}"

echo "Database name from config: ${databasename}"
dea-test-env -C "$CONFIGFILE" teardown
sleep 2s
createdb -h agdcdev-db.nci.org.au -p 6432 "$databasename"

echo "Loading module ${MODULE}"
echo ""

# Check if we can connect to the database
datacube -C "$CONFIGFILE" system check

# Run the initialise Test Database Script
# Dea-System Init adds all the products to the database (i.e., No need to do datacube product add)
# datacube product add ~/PycharmProjects/digitalearthau/digitalearthau/config/products/*.yaml
dea-system -C "$CONFIGFILE" init

# Check if we can connect to the database
datacube -vv -C "$CONFIGFILE" system check

sh dea_testscripts/index_and_ingest.sh "$CONFIGFILE" "$WORKDIR"

EOF