#!/bin/bash

set -eu

while [[ $# -gt 0 ]]; do
    key="$1"
    case ${key} in
        --deamodule )           shift
                                MODULE=$1
                                ;;
        * )                     exit 0
    esac
    shift
done

HOMEDIR=$(pwd)

echo "
  ********************************************************************
   Executing the script from:  '$HOMEDIR'
  ********************************************************************"
echo ""

CONFIGFILE="$HOMEDIR"/datacube_config.conf
DCCONF="datacube_config.conf"

# Copy yaml files from repo
sh dea_testscripts/copy_yaml_files.sh "$HOMEDIR"

# Get database name from the config file
configname=""
databasename=""
while IFS=': ' read -r a b; do
    if [[ "$a" == "["* ]]; then
       configname=$a
    fi

    if [[ "$a" == "db_database" && "$configname" == "[datacube]" ]]; then
       databasename="$b"
    fi
done < "$CONFIGFILE"

# Check if output directory exists, else create one
[ -d "$HOMEDIR/output_files/idx_ingest" ] || mkdir -p "$HOMEDIR"/output_files/idx_ingest
[ -d "$HOMEDIR/output_files/stats" ] || mkdir -p "$HOMEDIR"/output_files/stats
[ -d "$HOMEDIR/output_files/fc" ] || mkdir -p "$HOMEDIR"/output_files/fc
[ -d "$HOMEDIR/output_files/nbconvert" ] || mkdir -p "$HOMEDIR"/output_files/nbconvert

echo "
  ===================================================================
  |  Env setup_module before index and ingest process : $MODULE      
  ==================================================================="
echo ""
# shellcheck source=/dev/null
echo Loading module "${MODULE}"
module use /g/data/v10/public/modules/modulefiles
module load "${MODULE}"

# Create a database file for testing purpose
# createdb -h agdcdev-db.nci.org.au -p 6432 "$databasename"

##################################################################################################
# Run a test index and ingest on NCI and Raijin system
##################################################################################################
echo "
  ===================================================================
  |  Test the following on NCI-VDI system:                          |
  |  1) Indexing  Telemetry, Level1 Scene, LS7_ETM_NBAR/NBART,      |
  |     LS8_OLITIRS_NBAR/NBART Scenes from the year 2016-2018       |
  |  2) And then ingesting the products to test database            |
  ==================================================================="
echo ""
sh "$HOMEDIR"/dea_testscripts/index_and_ingest.sh "$CONFIGFILE" "$HOMEDIR" > "$HOMEDIR"/output_files/idx_ingest/Index_Ingest_NCI_PC.log

echo "
  ===================================================================
  |  Test the following on Raijin system using PBS:                 |
  |  1) Indexing  Telemetry, Level1 Scene, LS7_ETM_NBAR/NBART,      |
  |     LS8_OLITIRS_NBAR/NBART Scenes from the year 2016-2018       |
  |  2) And then ingesting the products to test database            |
  ==================================================================="
echo ""

PSQL_LOG="$HOMEDIR"/output_files/Test_DEA_Module.log
psql -h agdcdev-db.nci.org.au -p 6432 -d "$databasename" -o "$PSQL_LOG" -L "$PSQL_LOG" << EOF
 select * from agdc.dataset_location;
 select id, metadata_type_ref, dataset_type_ref, archived, added, added_by from agdc.dataset;
 select id, name, added, added_by from agdc.metadata_type;
 select id, name, metadata from agdc.dataset_type;
 select * from agdc.dataset_source;
 select count(*) FROM agdc.dataset;
 select name, count(*) FROM agdc.dataset a, agdc.dataset_type b where a.dataset_type_ref = b.id group by b.name;
EOF
