#!/bin/bash

# Set echo, error for unset variables, and exit on fail
set -eux

while [[ "$#" -gt 0 ]]; do
    key="$1"
    case "${key}" in
        --profile )             shift
                                AWS_PROFILE="$1"
                                ;;
        --s3bucket )            shift
                                BUCKET="$1"
                                ;;
        --numdays )            shift
                                NUM_DAYS="$1"
                                ;;
        --enddate )            shift
                                END_DATE="$1"
                                ;;
        * )
          echo "Input key, '$key', did not match the expected input argument key"
          exit 1
          ;;
    esac
    shift
done

# This is a logging directory
WORKDIR=/g/data/v10/work/s2_nbar_rolling_archive/$(date '+%FT%H%M')
mkdir -p "${WORKDIR}"

# alex: num_days is the number of days prior to today to check for syncing
qsub -N s2nbar-rolling-archive -o "${WORKDIR}" -e "${WORKDIR}"  \
-v AWS_PROFILE="${AWS_PROFILE}",s3_bucket="${BUCKET}",num_days="${NUM_DAYS}",end_date="${END_DATE}", \
./execute_s2_to_s3_rolling.sh
