#!/bin/bash

ANSIBLE_INTERPRETER="/g/data2/v10/private/dea_lambda_orchestrator/raijin_scripts/deploy/trigger_env/bin/pyvenv"
args=$@

echo "Deploying ${args[0]}"
module load python3/3.5.2
source trigger_env/bin/activate
ansible-playbook -vv -i "localhost," -c local --extra-vars "ansible_python_interpreter=$ANSIBLE_INTERPRETER object_name=${args[0]}" ./deploy.yaml
