#!/bin/bash

set -eu

args=( "$@" )

if [[ "${args[0]}" == "dea_unstable" ]]; then
    rm -rf /g/data/v10/public/modules/dea/unstable
fi

echo "Deploying Environment Module ${args[0]}"
module load python3/3.7.4

python3 build_environment_module.py "${args[0]}"/modulespec.yaml
