#!/bin/bash

set -eu

while [[ $# -gt 0 ]]; do
    key="$1"
    case ${key} in
        --deamodule )           shift
                                MODULE=$1
                                ;;
        --year )                shift
                                YEAR=$1
                                ;;
        --queue )               shift
                                QUEUE=$1
                                ;;
        --project )             shift
                                PROJECT=$1
                                ;;
        --tag )                 shift
                                TAG=$1
                                ;;
        * )                     exit 0
    esac
    shift
done

modname=`echo "$MODULE" | sed -r "s/[/]+/_/g"`
WORKDIR=/g/data/v10/work/dea_env_test/"${modname}"
SUBMISSION_LOG="$WORKDIR"/log_files/deaenv_fc-$(date '+%F-%T').log
CONFIGFILE="$(pwd)"/datacube_config.conf

# Copy yaml files from repo
sh dea_testscripts/copy_fcyaml_files.sh "$WORKDIR"

# Check if output directory exists, else create one
mkdir -p "$WORKDIR"/output_files/fc
mkdir -p "$WORKDIR/log_files"
echo "Start time: " "$(date '+%F-%T')" > "$SUBMISSION_LOG"

# Get database name from the config file
configname=""
databasename=""
while IFS=': ' read -r a b; do
    if [[ "$a" == "["* ]]; then
       configname=$a
    fi

    if [[ "$a" == "db_database" && "$configname" == "[datacube]" ]]; then
       databasename="$b"
    fi
done < "$CONFIGFILE"

# This is required as FC code expects user to configure work root
# else work root shall be defaulted to '/g/data/v10/work/' folder
export DEA_WORK_ROOT="$WORKDIR/output_files/fc"

nohup "$SHELL" > "$SUBMISSION_LOG" 2>&1 << EOF &
echo "Logging results into: ${SUBMISSION_LOG}"
module use /g/data/v10/public/modules/modulefiles
module load "${MODULE}"

echo "Database name from config: ${databasename}"
echo "Loading module ${MODULE}"
echo ""

# Check if we can connect to the database
datacube -C "$CONFIGFILE" system check

# Run the initialise Test Database Script
dea-system -C "$CONFIGFILE" init

# Check if we can connect to the database
datacube -vv -C "$CONFIGFILE" system check

echo ""
# Redirect the PBS logs to log_files folder
cd "$WORKDIR/log_files" || exit 0

echo "Applying fractional cover on ls7_fc_albers product for the year ${YEAR}" with tag "${TAG}"
echo "------------------------------------------------------------------------------------------"
datacube-fc submit --app-config "$WORKDIR"/fc_configfiles/ls7_fc_albers.yaml --project "${PROJECT}" --queue "${QUEUE}" -C "$CONFIGFILE" -vvv --year "${YEAR}" --tag "${TAG}"

echo "Applying fractional cover on ls8_fc_albers product for the year ${YEAR}" with tag "${TAG}"
echo "------------------------------------------------------------------------------------------"
datacube-fc submit --app-config "$WORKDIR"/fc_configfiles/ls8_fc_albers.yaml --project "${PROJECT}" --queue "${QUEUE}" -C "$CONFIGFILE" -vvv --year "${YEAR}" --tag "${TAG}"

echo "Applying fractional cover on ls5_fc_albers product for the year ${YEAR}" with tag "${TAG}"
echo "------------------------------------------------------------------------------------------"
datacube-fc submit --app-config "$WORKDIR"/fc_configfiles/ls5_fc_albers.yaml --project "${PROJECT}" --queue "${QUEUE}" -C "$CONFIGFILE" -vvv --year "${YEAR}" --tag "${TAG}"

EOF
