homepage: "http://www.ga.gov.au/"

licence:
  name: "CC BY Attribution 4.0 International License"
  link: "https://creativecommons.org/licenses/by/4.0/"
  short_name: "CCA 4.0"
  copyright: "DEA, Geoscience Australia"

contact:
  name: "Geoscience Australia"
  organization: "Commonwealth of Australia"
  email: "sales@ga.gov.au"
  phone: "+61 2 6249 9966"
  url: "http://www.ga.gov.au"

provider:
  scheme: "s3"
  region: "ap-southeast-2"
  requesterPays: "False"
aws-domain: "https://data.dea.ga.gov.au"
root-catalog: "https://data.dea.ga.gov.au/catalog.json"
aws-products: ['fractional-cover/fc/v2.2.0/ls5', 'fractional-cover/fc/v2.2.0/ls8']

products:
  wofs_filtered_summary:
    description: "Wofs Filtered Summary algorithm ... "
    bands:
      confidence: "confidence"
      wofs_filtered_summary: "wofs filtered summary"
  wofs:
    description: "WoFS algorithm ... "
    bands:
      water: "water"
  fractional_cover:
    description: "The Fractional Cover (FC)"
    bands:
      PV: "Photosynthetic Vegetation"
      NPV: "Non-Photosynthetic Vegetation"
      BS: "Bare Soil"
      UE: "Unmixing Error"

