service: s3-directory-list

plugins:
  - serverless-plugin-existing-s3

custom:
  bucketName: datacube-core-deployment

provider:
  name: aws
  runtime: python3.6
  memorySize: 128

  stage: dev
  region: ap-southeast-2


  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "s3:ListBucket"
     Resource: {"Fn::Join": ["", ["arn:aws:s3:::", {"Ref": "ServerlessDeploymentBucket"}]]}
   - Effect: "Allow"
     Action:
       - "s3:PutObject"
     Resource:
       Fn::Join:
         - ""
         - - "arn:aws:s3:::"
           - "Ref": "ServerlessDeploymentBucket"
           - "/*"
   - Effect: "Allow"
     Action:
       - "s3:ListBucket"
     Resource: "arn:aws:s3:::${self:custom.bucketName}"
   - Effect: "Allow"
     Action:
       - "s3:GetObject"
       - "s3:PutObject"
     Resource: "arn:aws:s3:::${self:custom.bucketName}/*"
   - Effect: "Allow"
     Action:
      - "s3:PutBucketNotification"
     Resource: "arn:aws:s3:::${self:custom.bucketName}"

functions:
  generateListing:
    handler: genindex.generate_listing
    events:
      - existingS3:
          bucket: ${self:custom.bucketName}
          events:
            - s3:ObjectCreated:*
            - s3:ObjectRemoved:*
