#!/bin/bash

set -eu

while [[ $# -gt 0 ]]; do
    key="$1"
    case ${key} in
        --deamodule )           shift
                                MODULE=$1
                                ;;
        * )                     exit 0
    esac
    shift
done

modname=$(echo "$MODULE" | sed -r "s/[/]+/_/g")
WORKDIR=/g/data/v10/work/dea_env_test/"${modname}"/nbconvert
SUBMISSION_LOG="$WORKDIR"/deaenv_nbconvert-$(date '+%F-%T').log
HOMEDIR="$(pwd)"

# Create output work directory (if not exists)
mkdir -p "$WORKDIR"

echo "Start time: " "$(date '+%F-%T')" > "$SUBMISSION_LOG"

nohup "$SHELL" > "$SUBMISSION_LOG" 2>&1 << EOF &
cd "$WORKDIR"
echo "Logging results into: ${SUBMISSION_LOG}"
qsub -v MODULE="$MODULE",TEST_BASE="$HOMEDIR",OUTDIR="$WORKDIR" "$HOMEDIR"/dea_testscripts/nbconvert_execute.sh

EOF