#!/bin/bash
set -eu

while [[ "$#" -gt 0 ]]; do
    key="$1"
    case "${key}" in
        --year )                shift
                                YEAR="$1"
                                ;;
        --product )             shift
                                PRODUCT="$1"
                                ;;
        --dea-module )          shift
                                MODULE="$1"
                                ;;
        --queue )               shift
                                QUEUE="$1"
                                ;;
        --stage )               shift
                                STAGE="$1"
                                ;;
        --project )             shift
                                PROJECT="$1"
                                ;;
        * )
          echo "Input key, '$key', did not match the expected input argument key"
          exit 1
          ;;
    esac
    shift
done

# Override echo command to prepend timestamp before echo message
echo() {
    command echo "$(date '+%F_%T.%N')" "$@"
}

WORKDIR=/g/data/v10/work/ingest/"${PRODUCT}"/$(date '+%FT%H%M')
SUBMISSION_LOG="${WORKDIR}"/ingest-${PRODUCT}-$(date '+%F-%T').log
JOB_NAME="${PRODUCT}_${YEAR}"
count=0
dbhostname='agdcdev-db.nci.org.au'
dbport='6432'
dbname='datacube'

mkdir -p "${WORKDIR}"
echo "Start time: " "$(date '+%F-%T')" > "$SUBMISSION_LOG"

module use /g/data/v10/public/modules/modulefiles
module load "${MODULE}"
while read -r LINE; do
  if [[ "$count" -eq 1 ]]
  then
      dbhostname="$(cut -d' ' -f2 <<<"$LINE")"
      count="$((count+1))"
  elif [[ "$count" -eq 2 ]]
  then
      dbport="$(cut -d' ' -f2 <<<"$LINE")"
      count="$((count+1))"
  elif [[ "$count" -eq 3 ]]
  then
      dbname="$(cut -d' ' -f2 <<<"$LINE")"
      count="$((count+1))"
  fi

  if [[ "${STAGE}" == "dev"  && "$LINE" == "[dea-dev]" ]]; then
      count="$((count+1))"
  fi

  if [[ "${STAGE}" == "prod"  && "$LINE" == "[datacube]" ]]; then
      count="$((count+1))"
  fi
done  < "$DATACUBE_CONFIG_PATH"

# Launch the submission in the background, outputting results to a log file
cd "${WORKDIR}"

nohup "$SHELL" > "$SUBMISSION_LOG" 2>&1 <<EOF &
echo "Logging job: ${JOB_NAME} into: ${SUBMISSION_LOG}"
echo ""
echo Loading module ${MODULE}
echo ""

# Check if we can connect to the database
datacube -vv system check

# Read agdc datasets from the database before ingest process
echo ""
echo "**********************************************************************"
echo "Read previous agdc_dataset product names and count before ingest process"
echo "Connected to the database host name: ${dbhostname}"
echo "Connected to the database port number: ${dbport}"
echo "Connected to the database name: ${dbname}"
psql -h ${dbhostname} -p ${dbport} -d ${dbname} \
  -c 'select name, count(*) FROM agdc.dataset a, agdc.dataset_type b where a.dataset_type_ref = b.id group by b.name'
echo "**********************************************************************"

echo ""
echo "Executing ${PRODUCT} ingest for the ${YEAR}"
##################################################################################################
# Run dea-submit-ingest process
##################################################################################################
yes Y | dea-submit-ingest qsub --project "${PROJECT}" --queue "${QUEUE}" -n 1 -t 15 --allow-product-changes \
  --name "${JOB_NAME}" "${PRODUCT}" "${YEAR}"
EOF

# Log the following values to the terminal, to be processed by the orchestration lambda function
echo ingest_log="${SUBMISSION_LOG}"
echo ingest_pbs_job_name="${JOB_NAME}"
echo ingest_project="${PROJECT}"
echo ingest_job_queue="${QUEUE}"
echo ingest_work_dir="${WORKDIR}"
echo ingest_product="${PRODUCT}"
