#!/bin/bash
set -eu

while [[ "$#" -gt 0 ]]; do
    key="$1"
    case "${key}" in
        --year )                shift
                                YEAR="$1"
                                ;;
        --product )             shift
                                PRODUCT="$1"
                                ;;
        --tag )                 shift
                                TAG="$1"
                                ;;
        --dea-module )          shift
                                MODULE="$1"
                                ;;
        --queue )               shift
                                QUEUE="$1"
                                ;;
        --project )             shift
                                PROJECT="$1"
                                ;;
        --stage )               shift
                                STAGE="$1"
                                ;;
        * )
          echo "Input key, '$key', did not match the expected input argument key"
          exit 1
          ;;
    esac
    shift
done

# Override echo command to prepend timestamp before echo message
echo() {
    command echo "$(date '+%F_%T.%N')" "$@"
}

OUTPUT_DIR=/g/data/v10/work/"${PRODUCT}"/wofs/$(date '+%Y-%m')
LOG_FILENAME="${PRODUCT}"-$(date '+%F-%T').log
SUBMISSION_LOG="$OUTPUT_DIR/$LOG_FILENAME"
JOB_NAME="${YEAR}_${PRODUCT}"
count=0
dbhostname='agdcdev-db.nci.org.au'
dbport='6432'
dbname='datacube'

mkdir -p "$OUTPUT_DIR"
echo "Start time: " "$(date '+%F-%T')" > "$SUBMISSION_LOG"

module use /g/data/v10/public/modules/modulefiles
module load "${MODULE}"

while read -r LINE; do
  if [[ "$count" -eq 1 ]]
  then
      dbhostname="$(cut -d' ' -f2 <<<"$LINE")"
      count="$((count+1))"
  elif [[ "$count" -eq 2 ]]
  then
      dbport="$(cut -d' ' -f2 <<<"$LINE")"
      count="$((count+1))"
  elif [[ "$count" -eq 3 ]]
  then
      dbname="$(cut -d' ' -f2 <<<"$LINE")"
      count="$((count+1))"
  fi

  if [[ "${STAGE}" == "dev"  && "$LINE" == "[dea-dev]" ]]; then
      count="$((count+1))"
  fi

  if [[ "${STAGE}" == "prod"  && "$LINE" == "[datacube]" ]]; then
      count="$((count+1))"
  fi
done < "$DATACUBE_CONFIG_PATH"

cd "$OUTPUT_DIR" || exit 1
APP_CONFIG=/g/data/v10/public/modules/"$MODULE"/wofs/config/"${PRODUCT}".yaml

# Launch the submission in the background, outputting results to a log file
nohup "$SHELL" >> "$SUBMISSION_LOG" 2>&1 <<EOF &
echo "Logging job: ${JOB_NAME} into: ${SUBMISSION_LOG}"
echo ""
echo Loading module "${MODULE}"
echo ""

module use /g/data/v10/public/modules/modulefiles
module load "${MODULE}"

# Check if we can connect to the database
datacube -vv system check

# Read agdc datasets from the database before wofs process
echo ""
echo "**********************************************************************"
echo "Read previous agdc_dataset product names and count before wofs process"
echo "Connected to the database host name: ${dbhostname}"
echo "Connected to the database port number: ${dbport}"
echo "Connected to the database name: ${dbname}"
psql -h ${dbhostname} -p ${dbport} -d ${dbname} \
  -c 'select name, count(*) FROM agdc.dataset a, agdc.dataset_type b where a.dataset_type_ref = b.id group by b.name'
echo "**********************************************************************"

echo ""
echo "Executing wofs for ${YEAR} ${PRODUCT} with tag ${TAG}"
##################################################################################################
# Run datacube-wofs submit two stage PBS job
##################################################################################################
datacube-wofs submit -v -v --project "${PROJECT}" --queue "${QUEUE}" --year "${YEAR}" --app-config "${APP_CONFIG}" \
   --tag "${TAG}"
EOF

# Log the following values to the terminal, to be processed by the orchestration lambda function
echo wofs_log="${SUBMISSION_LOG}"
echo wofs_pbs_job_name="${JOB_NAME}"
echo wofs_project="${PROJECT}"
echo wofs_job_queue="${QUEUE}"
echo wofs_work_dir="${OUTPUT_DIR}"
echo wofs_product="${PRODUCT}"
