name: dea-env
channels:
- conda-forge
dependencies:
- affine
- attrs
- awscli
- basemap
- black
- boltons
- boto3
- botocore
- bottleneck
- bqplot
- cachetools
- cairo
- cartopy
- cffi
- ciso8601
- click
- click-plugins
- cligj
- cmake
- cmocean
- compliance-checker
- colour
- conda
- conda-env
- curl
- cvxopt
- cvxpy
- cython
- dask
- descartes
- distributed
- docutils
- expat
- eventlet
- brittainhard::fancyimpute
- flask
- flask-caching
- fiona
- folium
- fontconfig
- freetype
- freexl
- future
- gdal
- geopandas
- geopy
- geos
- geotiff
- gettext
- anaconda::gevent
- giflib
- glib
- glue-geospatial
- glueviz
- gunicorn
- h5py
- hdbscan
- hdf4
- hdf5
- hypothesis
- icu
- importlib_resources
- intel-openmp
- ipdb
- ipyleaflet
- ipympl
- ipython-sql
- ipywidgets
- jmespath
- joblib
- jpeg
- jplephem
- json-c
- jsonschema
- jupyter
- jupyter_contrib_nbextensions
- jupyter_dashboards
- jupyterlab
- kealib
- keras
- krb5
- lark-parser
- libgdal
- libgfortran
- libgfortran-ng
- libnetcdf
- line_profiler
- luigi
- matplotlib
- memory_profiler
- anaconda::mkl-service
- intel::mkl
- mkl_fft
- anaconda::mkl-include
- mkl_random
- mock
- modernize
- moto
- mpi4py
- munch
- mypy
- nb_conda_kernels
- nbdime
- netcdf4
- nodejs
- notebook
- numba
- numexpr
- numpy
- openjpeg
- openmpi
- pandas
- parallel
- anaconda::paramiko
- parse
- pcre
- pep8
- perf
- pip
- pixman
- plotly
- poppler
- poppler-data
- proj4
- prometheus_client
- psutil
- psycopg2
- pthread-stubs
- pudb
- pyephem
- pydash
- pylint
- pyparsing
- pypeg2
- pysolar
- pytables
- pytest
- pytest-cov
- python
- python-dateutil
- pyyaml
- qgis
- bashtage::randomgen
- rasterio
- rasterstats
- recommonmark
- redis
- redis-py
- anaconda::requests
- rios
- rsgislib
- rtree
- s3transfer
- scikit-image
- scikit-learn
- scipy
- seaborn
- setuptools
- shapely
- simplejson
- singledispatch
- skyfield
- snuggs
- spectral
- sphinx
- sphinx_rtd_theme
- spyder
- sqlalchemy
- sqlite
- structlog
- jjhelmus::tensorflow  # Import issue workaround, https://github.com/conda-forge/tensorflow-feedstock/issues/11
- tornado
- tmux
- tqdm
- tuiview
- typing
- vega_datasets
- voluptuous
- watchdog
- widgetsnbextension
- xarray
- xerces-c
- xgboost
- yaml
- yamllint
- yappi
- yarn
- zarr
- pip:
  - apscheduler
  - celery
  - checksumdir
  - click-datetime
  - dask_labextension
  - DAWG
  - ffmpeg-python
  - graphviz
  - hdmedians
  - jupyterlab-git
  - jupyter-server-proxy  # port forwards, useful for dask dashboards
  - libtmux
  - meinheld
  - ptpython
  - Py6S
  - pyDEM
  - python-intervals
  - requests-aws4auth
