name: dea-env
channels:
- conda-forge
- brittainhard
dependencies:
- affine
- attrs
- basemap
- black
- bottleneck
- boto3
- bqplot
- botocore
- cachetools
- cairo
- cartopy
- click
- click-plugins
- cligj
- cmocean
- compliance-checker
- conda
- conda-env
- curl
- cvxopt
- cvxpy
- cython
- dask == 0.19.3  # Datacube ingest app has an issue (datacube-core issue #658), with version later than this
- distributed == 1.23.3  # Datacube ingest app has an issue (datacube-core issue #658), with version later than this
- docutils
- ephem
- expat
- fancyimpute
- fiona
- folium
- fontconfig
- future
- freetype
- freexl
- gdal
- geopandas
- geopy
- geos
- geotiff
- gettext
- giflib
- glib
- glueviz
- glue-geospatial
- graphviz  # This is only graphviz itself, not the python bindings. The latter are in the pip section.
- hdbscan
- hdf4
- hdf5
- h5py
- hypothesis
- icu
- intel-openmp
- ipdb
- ipyleaflet
- ipympl
- ipywidgets
- jmespath
- joblib
- jpeg
- jplephem
- json-c
- jsonschema
- jupyter
- jupyter_contrib_nbextensions
- jupyter_dashboards
- jupyterlab
- keras
- kealib
- krb5
- libgdal
- libgfortran
- libgfortran-ng
- libnetcdf
- line_profiler
- luigi
- matplotlib
- memory_profiler
# - mkl-service
- mkl
- mkl_fft
- mkl_random
- mock
- mpi4py
- munch
- nb_conda_kernels
- netcdf4
- nodejs
- notebook
- numba
- numexpr
- numpy >= 1.16
- openjpeg
- pandas
- parallel
- pcre
- pep8
- pixman
- plotly
- poppler
- poppler-data
- proj4
- psutil
- pthread-stubs
- psycopg2
- py6s
- pylint
- pyparsing
- pytables
- pytest
- pytest-cov
- python >= 3.6.6
- python-dateutil
- pyyaml
- rasterio >= 1.0.15
- rasterstats
- recommonmark
- redis
- redis-py == 2.10.6  # FC, wofs, and datacube-stats app has an issue (digitalearthau issue #205), with later revisions
- rios
- rtree
- s3transfer
- scikit-image
- scikit-learn
- scipy
- seaborn
- shapely
- simplejson
- singledispatch
- snuggs
- spectral
- sphinx
- sphinx_rtd_theme
- spyder
- sqlalchemy
- sqlite
- tensorflow == 1.9.0  # Import issue workaround, https://github.com/conda-forge/tensorflow-feedstock/issues/11
- tornado
- tqdm
- tuiview
- vega_datasets
- voluptuous
- widgetsnbextension
- xarray
- xerces-c
- xgboost
- yaml
- yarn
- pip:
  - autopep8
  - awscli
  - boltons
  - celery
  - checksumdir
  - ciso8601
  - click-datetime
  - DAWG
  - ffmpeg-python
  - flask
  - Flask-Caching
  - graphviz
  - gunicorn
  - hdmedians
  - ipython-sql
  - meinheld
  - modernize
  - mypy
  - opencv-python
  - parse
  - perf
  - pudb
  - pydash
  - pyDEM
  - pypeg2
  - structlog[dev]
  - yamllint
  - yappi
