name: dea-env
channels:
- conda-forge
- defaults
- nodefaults
dependencies:
- basemap
- bottleneck
- bqplot
- cachetools
- cartopy
- certifi
- click
- compliance-checker
- cython
- dask
- distributed
- ephem
- fiona
- folium
- future
- gdal >= 2.2.4
- geopandas
- geopy
- glueviz
- graphviz  # This is only graphviz itself, not the python bindings. The latter are in the pip section.
- h5py
- hdf5
- hypothesis
- ipdb
- ipyleaflet
- ipympl
- ipywidgets
- jplephem
- jsonschema
- jupyter
- jupyter_contrib_nbextensions
- jupyter_dashboards
- jupyterlab
- keras
- line_profiler
- luigi
- matplotlib
- memory_profiler
  #- mkl-service
- mock
- netcdf4
- nodejs
- numba
- numexpr
- numpy
  #- openblas
- openssl
- pandas
- pep8
- pip
- plotly
- psutil
- psycopg2
- py6s
- pylint
- pytables
- pytest
- pytest-cov
- pyyaml
- python = 3.6
# - qgis >= 3  # QGIS 3 is not being built for linux64 yet. See https://github.com/conda-forge/qgis-feedstock/pull/36
- rasterio >= 1.0.2  # required for zip reading
- rasterstats
- redis
- redis-py
- rios
  #- rsgislib # Seems to pull in old gdal
- rtree
- scikit-image
- scikit-learn
- scipy
- seaborn
- shapely
- singledispatch
- spectral
- sphinx
- spyder
- sqlalchemy
- tqdm
- tuiview
- xarray
- voluptuous
- pip:
  - autopep8
  - awscli
  - boltons
  - celery >= 4
  - ciso8601
  - click-datetime
  - DAWG
  - flask
  - Flask-Caching
  - graphviz
  - gunicorn
  - hdmedians
  - ipython-sql
  - meinheld
  - modernize
  - mypy
  - opencv-python
  - perf
  - pudb
  - pydash
  - pyDEM
  - pypeg2
  - structlog[dev]
  - yamllint
  - yappi
