variables:
  module_name: dea-env
  module_description: DEA Environment Module
  modules_dir: "/g/data/v10/public/modules"
  conda_path: "/g/data/v10/private/miniconda3-new/bin/conda"
  python_version: 3.6

# These templated variables are filled and included in the available variables used
# in template files and configuration sections below
templated_variables:
  module_path: "{modules_dir}/{module_name}/{module_version}"
  python_path: "{modules_dir}/{module_name}/{module_version}/lib/python{python_version}/site-packages/"

install_conda_packages: environment.yaml

dea_env_miniconda3: reinstall_miniconda.sh

install_pip_packages:
  requirements: pip_install_packages.txt
  prefix: "{module_path}"
  pip_cmd: "{module_path}/bin/pip "

copy_files:
- src: environment.yaml
  dest: "{modules_dir}/{module_name}/{module_version}/environment.yaml"
- src: pip_install_packages.txt
  dest: "{module_path}/pip_install_packages.txt"

template_files:
- src: modulefile.template
  dest: "{modules_dir}/modulefiles/{module_name}/{module_version}"
  chmod: 0o444

finalise_commands:
- jupyter labextension install --no-build jupyterlab_bokeh
- jupyter labextension install --no-build @jupyterlab/geojson-extension
- jupyter labextension install --no-build @jupyterlab/github
- jupyter labextension install --no-build @jupyterlab/toc
- jupyter labextension install --no-build @jupyter-widgets/jupyterlab-manager
- jupyter lab build
