service: ncimonitoring

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

# See https://github.com/UnitedIncome/serverless-python-requirements
# Or https://github.com/ubaniabalogun/serverless-package-python-functions

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters

custom:
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.6
  region: ap-southeast-2
  memorySize: 512
  stage: prod
  deploymentBucket:
    name: dea-lambda
  stackTags:
    repo: dea-orchestration
    author: damien.ayers@ga.gov.au
    purpose: nci-monitoring
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ssm:GetParameters'
        - 'ssm:DescribeParameters'
      Resource:
        - "arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/orchestrator.*"
        - "arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/pipeline.*"
    - Effect: 'Allow'
      Action: 'kms:Decrypt'
      Resource:
        - "arn:aws:kms:#{AWS::Region}:#{AWS::AccountId}:key/efba9b4c-8e64-430c-86c9-f00eaf69e582"
    - Effect: 'Allow'
      Action: 's3:GetObject'
      Resource: 'arn:aws:s3:::datacube-core-deployment/*'
    - Effect: 'Allow'
      Action: 'cloudwatch:PutMetricData'
      Resource: '*'

functions:
  checkQuotas:
    handler: handler.hello
    events:
      - schedule: rate(1 hour)
