#!/bin/bash

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
LAMBDA_NAME="$1"

pushd "$(pwd -P)"
cd "$SCRIPT_DIR/.." || exit 1

case $LAMBDA_NAME in
    all)
        find . -name "requirements.txt" | sort -r | sed -e 's/^/-r /' | xargs python3 -m pip install ;;
    *)
        if [[ ! -f "./lambda_functions/$LAMBDA_NAME"/requirements.txt ]]; then
            echo "Unable to find requirements.txt for '$LAMBDA_NAME'"
            popd
            exit 1
        fi

        python3 -m pip install --upgrade -r "./lambda_functions/$LAMBDA_NAME"/requirements.txt;;
esac

popd
exit 0
