#!/bin/bash
set -eux
HOME_PATH=/g/data/u46/users/sm9911/temp_repo
while [[ "$#" -gt 0 ]]; do
    key="$1"
    case "${key}" in
        --dea-module )          shift
                                MODULE="$1"
                                ;;
        --queue )               shift
                                QUEUE="$1"
                                ;;
        --project )             shift
                                PROJECT="$1"
                                ;;
        --cog-product )         shift
                                PRODUCT="$1"
                                ;;
        --time-range )          shift
                                RANGE_EXP="$*"
                                break # Last input argument and hence exiting while loop
                                ;;
        * )
          echo "Input key, '$key', did not match the expected input argument key"
          exit 1
          ;;
    esac
    shift
done

WORKDIR=/g/data/v10/work/cog_conversion/"$PRODUCT"/$(date '+%F_%H-%M-%S')
SUBMISSION_LOG="$WORKDIR"/Cog_Submission_$(date '+%s').log
START_YEAR=$(echo "$RANGE_EXP" | cut -f 1 -d '-')
END_YEAR=$(echo "$RANGE_EXP" | cut -f 2 -d '-')

mkdir -p "${WORKDIR}"

module use /g/data/v10/public/modules/modulefiles
module load "${MODULE}"

TIME_RANGE_TO_PROCESS="'$START_YEAR < time < $END_YEAR'"

echo "Start time: $(date '+%F-%T')

Loading module ${MODULE}

# Check if we can connect to the database
$(datacube -vv system check)
" > "$SUBMISSION_LOG"

cd "${WORKDIR}"

echo ""
echo "Starting Cog-Conversion process for the period ${TIME_RANGE_TO_PROCESS}......"

nohup "$SHELL" >> "$SUBMISSION_LOG" 2>&1 << EOF &
##################################################################################################
# Qsub cog-convert process
##################################################################################################

python3 "$HOME_PATH"/COG-Conversion/converter/cog_conv_app.py qsub-cog-convert -q ${QUEUE} -P ${PROJECT} -p ${PRODUCT} \
--walltime 20 --output-dir ${WORKDIR} --time-range ${TIME_RANGE_TO_PROCESS}
EOF
