#!/usr/bin/env bash

#####################################################################################
# PBS job has been scheduled in the following sequence:
#    1) NBConvert pbs job shall run first (express queue)
#    2) DEA-Sync pbs job shall run after NBConvert job completes (express queue)
#    3) DEA-Submit-Ingest pbs job shall run after sync jobs completes (express queue)
#    4) Datacube-fc pbs job shall run after ingest jobs (normal queue)
#    5) Datacube-wofs pbs job shall run after fc jobs (normal queue)
#    6) Datacube-stats pbs job shall run after wofs jobs (normal queue)
#
#    TODO: Need resolve datacube-fc/wofs/stats dependencies on ingest jobs.
#          Instead of assuming normal jobs will take longer time to schedule
#          and by then ingest jobs have completed, we need to make fc/wofs 
#          hold job till dea-submit-ingest jobs has completed.
#####################################################################################

set -eu

while [[ $# -gt 0 ]]; do
    key="$1"
    case ${key} in
        --deamodule )           shift
                                MODULE=$1
                                ;;
        --testdir )             shift
                                TESTDIR=$1
                                ;;
        * )                     exit 0
    esac
    shift
done

modname=$(echo "$MODULE" | sed -r "s/[/]+/_/g")
WORKDIR=/g/data/v10/work/dea_env_test/test"$modname"-$(date '+%d%m%yT%H%M')
LOGFILE="$WORKDIR"/'Not_World_Readable_Files.log'

CONFIGFILE="$TESTDIR/datacube_config.conf"

# Ensure that all files are world readable
if [[ -n $(find "/g/data/v10/public/modules/$MODULE" ! -perm -o=r) ]]; then
    echo "
          Error: Some files in $MODULE are not world readable
          Following files in $MODULE are not world readable:
          -----------------------------------------------------------------"
          find /g/data/v10/public/modules/"$MODULE" ! -perm -o=r > "$LOGFILE"
    exit 0
fi

# Get database name from the config file
configname=""
databasename=""
while IFS=': ' read -r a b; do
    if [[ "$a" == "["* ]]; then
       configname=$a
    fi

    if [[ "$a" == "db_database" && "$configname" == "[datacube]" ]]; then
       databasename="$b"
    fi
done < "$CONFIGFILE"

module use /g/data/v10/public/modules/modulefiles/
module load "$MODULE"
export DATACUBE_CONFIG_PATH="$CONFIGFILE"

dea-test-env -C "$CONFIGFILE" teardown

# Create a database file for testing purpose
createdb -h agdcdev-db.nci.org.au -p 6432 "$databasename"

# Run the initialise Test Database Script
# Dea-System Init adds all the products to the database (i.e., No need to do datacube product add)
# datacube product add ~/PycharmProjects/digitalearthau/digitalearthau/config/products/*.yaml
dea-system -C "$CONFIGFILE" init

datacube -v -C "$CONFIGFILE" system check

# Create work directory
mkdir -p "$WORKDIR"/work/ingest/001
mkdir -p "$WORKDIR"/work/sync
mkdir -p "$WORKDIR"/work/stats/001
mkdir -p "$WORKDIR"/work/fc/001
mkdir -p "$WORKDIR"/work/nbconvert
mkdir -p "$WORKDIR"/work/wofs/001

# Copy the dsm1sv10 product definition from the production database to a temp yaml file
# This file shall be used to update the test database product definition (consumed by WOfS processing)
datacube -C "$CONFIGFILE" -E production product show dsm1sv10 > "$WORKDIR/dsm.yaml"

# Copy yaml files from repo
sh "$TESTDIR"/dea_testscripts/copy_yaml_files.sh "$WORKDIR" "$TESTDIR"

echo "
===================================================================
  Module under test : $MODULE
==================================================================="

echo "
##################################################################################################
# Run a dea-env-test nbconvert on requirements_met.ipynb file using PBS job submission
##################################################################################################"

cd "$WORKDIR/work/nbconvert" || exit 0
set -x  # echo is on

qsub -v MUT="$MODULE",WORKDIR="$WORKDIR",TESTDIR="$TESTDIR", "$TESTDIR"/dea_testscripts/pbs_nbconvert_script.sh

set +x  # echo is off

echo "
##################################################################################################
# Run a dea-env-test sync using PBS job submission
##################################################################################################"
## Declare datacube array of yaml files to download
declare -a sync_path_array=(
"/g/data/rs0/scenes/nbar-scenes-tmp/ls8/2018/01/output/nbart/LS8_OLITIRS_NBART_P54_GANBART01-032_092_085_20180109"
"/g/data/rs0/scenes/nbar-scenes-tmp/ls8/2018/06/output/nbar/LS8_OLITIRS_NBAR_P54_GANBAR01-032_100_071_20180610")

cd "$WORKDIR"/work/sync || exit 0

for i in "${sync_path_array[@]}"
do
    set -x  # echo is on

    # Fetch pbs job id's
    sync_job=$(qsub -V -v WORKDIR="$WORKDIR",MUT="$MODULE",PATH_TO_PROCESS="$i",DBNAME="$databasename",\
TESTDIR="$TESTDIR", "$TESTDIR"/dea_testscripts/dea-sync.sh)

    set +x  # echo is off
done

echo "
##################################################################################################
# Run a dea-env-test ingest using PBS job submission
##################################################################################################"
cd "$WORKDIR"/work || exit 0
# Migrate sample scenes from production database for testing purpose
set -x  # echo is on

migrate_job=$(qsub -W depend=afterok:"$sync_job" -P v10 -q express -l walltime=01:00:00,mem=1GB \
-v CONFIGFILE="$CONFIGFILE",MUT="$MODULE",TEMP_DIR="$WORKDIR", "$TESTDIR"/dea_testscripts/migrate_from_production_db.sh)

set +x  # echo is off

## Declare datacube array of yaml files to download
declare -a albers_yaml_array=("ls8_nbart_albers.yaml"
                              "ls8_nbar_albers.yaml"
                              "ls8_pq_albers.yaml")

cd "$WORKDIR"/work/ingest || exit 0

for i in "${albers_yaml_array[@]}"
do
  productname=$(echo "$i" | cut -f 1 -d '.')

  set -x  # echo is on

  ingest_job=$(qsub -V -W depend=afterok:"$migrate_job" \
-v WORKDIR="$WORKDIR",PRODUCT="$productname",MUT="$MODULE",YEAR=2018,CONFIGFILE="$CONFIGFILE",DBNAME="$databasename",\
TESTDIR="$TESTDIR", "$TESTDIR"/dea_testscripts/dea-submit-ingest.sh)

  set +x  # echo is off
done

echo "
##################################################################################################
# Run a dea-env-test FC using PBS job submission
##################################################################################################"
cd "$WORKDIR"/work/fc || exit 0
set -x  # echo is on

fc_job="$(qsub -V -W depend=afterok:"$ingest_job" \
-v WORKDIR="$WORKDIR",MUT="$MODULE",YEAR=2018,CONFIGFILE="$CONFIGFILE",DBNAME="$databasename",TESTDIR="$TESTDIR", \
"$TESTDIR"/dea_testscripts/datacube-fc.sh)"

set +x  # echo is off

echo "
##################################################################################################
# Run a dea-env-test WOfS using PBS job submission
##################################################################################################"
cd "$WORKDIR"/work/wofs || exit 0
set -x  # echo is on

wofs_job="$(qsub -V -W depend=afterok:"$ingest_job" \
-v WORKDIR="$WORKDIR",MUT="$MODULE",YEAR=2018,CONFIGFILE="$CONFIGFILE",DBNAME="$databasename",TESTDIR="$TESTDIR", \
"$TESTDIR"/dea_testscripts/datacube-wofs.sh)"

set +x  # echo is off

echo "
##################################################################################################
# Run a datacube-stats using PBS job submission
##################################################################################################"
declare -a stats_yaml_array=("item_10"
                             "nbar_ls8_2018_simple_normalised_difference"
                             "nbar_ls8_2018_geomedian"
                             "nbar_ls8_2018_new_geomedian"
                             "nbar_ls8_2018_spectral_mad"
                             "nbar_ls8_2018_tcwbg"
                             "nbar_ls8_2018_tcwbg_shapefile"
                             "nbar_ls8_2018_wet_geomedian_shapefile"
                             "nbar_ls8_2018_simple"
                             "nbar_ls8_2018_simple_shapefile"
                             "pq_count_albers_all_masked_multi_count"
                             "pq_count_albers_annual_shapefile"
                             "fc_ls8_2018_medoid"
                             "fc_ls8_2018_medoid_shapefile"
                             "fc_ls8_2018_medoid_simple"
                             "fc_ls8_2018_medoid_simple_shapefile"
                             "fc_percentile_albers"
                             "fc_percentile_albers_shapefile"
                             "wofsstats"
                             "wofsstats_shapefile"
                             "fc_ls8_2018_medoid_no_prov"
                             "fc_ls8_2018_medoid_no_prov_shapefile"
                             "fc_ls8_2018_none"
                             "fc_ls8_2018_none_shapefile"
                             "fc_ls8_2018_percentile_no_prov"
                             "fc_ls8_2018_percentile_no_prov_shapefile")

cd "$WORKDIR"/work/stats || exit 0

for i in "${stats_yaml_array[@]}"
do
  set -x  # echo is on

  qsub -V -W depend=afterok:"$wofs_job":"$fc_job" -v WORKDIR="$WORKDIR",MUT="$MODULE",PRODUCT="$i",\
CONFIGFILE="$CONFIGFILE",DBNAME="$databasename",TESTDIR="$TESTDIR", "$TESTDIR"/dea_testscripts/datacube-stats.sh

  set +x  # echo is off

done
