#!/bin/bash

set -eu

while [[ $# -gt 0 ]]; do
    key="$1"
    case ${key} in
        --deamodule )           shift
                                MODULE=$1
                                ;;
        * )                     exit 0
    esac
    shift
done

WORKDIR=/g/data/v10/work/dea_env_test
SUBMISSION_LOG="$WORKDIR"/log_files/test_deaenv_stats-$(date '+%F-%T').log
CONFIGFILE="$(pwd)"/datacube_config.conf

# Copy yaml files from repo
sh dea_testscripts/cp_statsyaml_files.sh "$WORKDIR" "$(pwd)"

# Check if output directory exists, else create one
[ -d "$WORKDIR/output_files/stats" ] || mkdir -p "$WORKDIR"/output_files/stats
mkdir -p "$WORKDIR/log_files"
echo "Start time: " $(date '+%F-%T') > "$SUBMISSION_LOG"

# Get database name from the config file
configname=""
databasename=""
while IFS=': ' read -r a b; do
    if [[ "$a" == "["* ]]; then
       configname=$a
    fi

    if [[ "$a" == "db_database" && "$configname" == "[datacube]" ]]; then
       databasename="$b"
    fi
done < "$CONFIGFILE"
dcdb="datacube"

nohup "$SHELL" > "$SUBMISSION_LOG" 2>&1 << EOF &
echo "Logging results into: ${SUBMISSION_LOG}"
module use /g/data/v10/public/modules/modulefiles
module load "${MODULE}"

echo "Loading module ${MODULE}"
echo ""

# Check if we can connect to the database
datacube -C "$CONFIGFILE" system check

# Run the initialise Test Database Script
# Dea-System Init adds all the products to the database (i.e., No need to do datacube product add)
# datacube product add ~/PycharmProjects/digitalearthau/digitalearthau/config/products/*.yaml
dea-system -C "$CONFIGFILE" init

# Check if we can connect to the database
datacube -vv -C "$CONFIGFILE" system check

echo ""
# If ncpus != 4 'qsub will throw an error: You have requested more memory per node (125.0GB) than the nodes in queue express can provide.'
datacube-stats -C "$CONFIGFILE" -vvv --log-queries --qsub 'project=u46,nodes=2,ncpus=4,walltime=1h,mem=medium,queue=express,name=nbar_stats,noask' "$WORKDIR"/stats_configfiles/nbar_stats.yaml
datacube-stats -C "$CONFIGFILE" -vvv --log-queries --qsub 'project=u46,nodes=2,ncpus=4,walltime=1h,mem=medium,queue=express,name=fc_stats_annual,noask' "$WORKDIR"/stats_configfiles/fc_stats_annual.yaml
datacube-stats -C "$CONFIGFILE" -vvv --log-queries --qsub 'project=u46,nodes=2,ncpus=4,walltime=1h,mem=medium,queue=express,name=fc_albseasonal,noask' "$WORKDIR"/stats_configfiles/fc_percentile_albers_seasonal.yaml
datacube-stats -C "$CONFIGFILE" -vvv --log-queries --qsub 'project=u46,nodes=2,ncpus=4,walltime=1h,mem=medium,queue=express,name=fc_albannual,noask' "$WORKDIR"/stats_configfiles/fc_percentile_albers_annual.yaml
datacube-stats -C "$CONFIGFILE" -vvv --log-queries --qsub 'project=u46,nodes=2,ncpus=4,walltime=1h,mem=medium,queue=express,name=fc_albers,noask' "$WORKDIR"/stats_configfiles/fc_percentile_albers.yaml

echo "
  ===================================================================
  | Add new stats product to the test database                      |
  ==================================================================="
echo ""
datacube -C "$CONFIGFILE" product add "$WORKDIR"/stats_configfiles/fc_percentile_albers.yaml
datacube -C "$CONFIGFILE" product add "$WORKDIR"/stats_configfiles/fc_percentile_albers_annual.yaml
datacube -C "$CONFIGFILE" product add "$WORKDIR"/stats_configfiles/fc_percentile_albers_seasonal.yaml
datacube -C "$CONFIGFILE" product add "$WORKDIR"/stats_configfiles/landsat_seasonal_mean.yaml
datacube -C "$CONFIGFILE" dataset add "$WORKDIR"/output_files/stats/001/SR_N_MEAN/*.nc

EOF