#!/bin/bash

set -eu

while [[ $# -gt 0 ]]; do
    key="$1"
    case ${key} in
        --deamodule )           shift
                                MODULE=$1
                                ;;
        --year )                shift
                                YEAR=$1
                                ;;
        --queue )               shift
                                QUEUE=$1
                                ;;
        --project )             shift
                                PROJECT=$1
                                ;;
        --tag )                 shift
                                TAG=$1
                                ;;
        * )                     exit 0
    esac
    shift
done

modname=$(echo "$MODULE" | sed -r "s/[/]+/_/g")
WORKDIR=/g/data/v10/work/dea_env_test/"${modname}"/fc
SUBMISSION_LOG="$WORKDIR"/fc-$(date '+%F-%T').log
DC_CONFIG_FILEPATH="$(pwd)"/datacube_config.conf

# Create output work directory (if not exists)
mkdir -p "$WORKDIR"/work

# Copy yaml files from repo
sh dea_testscripts/copy_fcyaml_files.sh "$WORKDIR"

echo "Start time: " "$(date '+%F-%T')" > "$SUBMISSION_LOG"

# This is required as FC code expects user to configure work root
# else work root shall be defaulted to '/g/data/v10/work/' folder
export DEA_WORK_ROOT="$WORKDIR/work"

module use /g/data/v10/public/modules/modulefiles
module load "${MODULE}"

[[ -z "${DATACUBE_CONFIG_PATH}" ]] && export DATACUBE_CONFIG_PATH="$DC_CONFIG_FILEPATH"

nohup "$SHELL" > "$SUBMISSION_LOG" 2>&1 << EOF &
echo "Logging results into: ${SUBMISSION_LOG}"
echo "Loading module ${MODULE}"
echo ""

# Check if we can connect to the database
datacube -vv -C "$DC_CONFIG_FILEPATH" system check

# Redirect the PBS logs to log_files folder
cd "$WORKDIR" || exit 0

echo ""
echo "Applying fractional cover on ls7_fc_albers product for the year ${YEAR}" with tag "${TAG}"
echo "------------------------------------------------------------------------------------------"
datacube-fc submit --app-config "$WORKDIR"/fc_configfiles/ls7_fc_albers.yaml --project "${PROJECT}" --queue "${QUEUE}" -C "$DC_CONFIG_FILEPATH" -vvv --year "${YEAR}" --tag "${TAG}"

echo "Applying fractional cover on ls8_fc_albers product for the year ${YEAR}" with tag "${TAG}"
echo "------------------------------------------------------------------------------------------"
datacube-fc submit --app-config "$WORKDIR"/fc_configfiles/ls8_fc_albers.yaml --project "${PROJECT}" --queue "${QUEUE}" -C "$DC_CONFIG_FILEPATH" -vvv --year "${YEAR}" --tag "${TAG}"

EOF