#!/bin/bash

set -eu

while [[ $# -gt 0 ]]; do
    key=$1
    case ${key} in
        --deamodule )           shift
                                MODULE=$1
                                ;;
        --queue )               shift
                                QUEUE=$1
                                ;;
        --project )             shift
                                PROJECT=$1
                                ;;
        * )                     exit 0
    esac
    shift
done

modname=$(echo "$MODULE" | sed -r "s/[/]+/_/g")
WORKDIR=/g/data/v10/work/dea_env_test/"${modname}"/stats
SUBMISSION_LOG="$WORKDIR"/stats-$(date '+%F-%T').log
CONFIGFILE="$(pwd)"/datacube_config.conf
LOGFILE="$WORKDIR"/'Not_World_Readable_Files.log'

# Create output work directory (if not exists)
mkdir -p "$WORKDIR"/nbar_stats/001
mkdir -p "$WORKDIR"/fc_stats/001

# Ensure that all files are world readable
if [[ $(find "/g/data/v10/public/modules/$MODULE" ! -perm -o=r) ]]; then
    echo "Error: Some files in $MODULE are not world readable"
    echo "
Following files in $MODULE are not world readable:
-----------------------------------------------------------------
$(find /g/data/v10/public/modules/"$MODULE" ! -perm -o=r)" > "$LOGFILE"
    exit 0
fi

# Copy yaml files from repo
sh dea_testscripts/cp_statsyaml_files.sh "$WORKDIR" "$(pwd)"

echo "Start time: " "$(date '+%F-%T')" > "$SUBMISSION_LOG"

nohup "$SHELL" > "$SUBMISSION_LOG" 2>&1 << EOF &
echo "Logging results into: ${SUBMISSION_LOG}"
module use /g/data/v10/public/modules/modulefiles
module load "${MODULE}"

echo "Loading module ${MODULE}"
echo ""

# Check if we can connect to the database
datacube -vv -C "$CONFIGFILE" system check

# Redirect the PBS logs to log_files folder
cd "$WORKDIR" || exit 0

echo ""
datacube-stats -C "$CONFIGFILE" -vvv --log-queries --qsub 'project=${PROJECT},nodes=2,ncpus=4,walltime=1h,mem=medium,queue=${QUEUE},name=nbar_stats,noask' "$WORKDIR"/stats_configfiles/nbar_stats.yaml
datacube-stats -C "$CONFIGFILE" -vvv --log-queries --qsub 'project=${PROJECT},nodes=2,ncpus=4,walltime=1h,mem=medium,queue=${QUEUE},name=fc_stats_annual,noask' "$WORKDIR"/stats_configfiles/fc_stats_annual.yaml
datacube-stats -C "$CONFIGFILE" -vvv --log-queries --qsub 'project=${PROJECT},nodes=2,ncpus=4,walltime=1h,mem=medium,queue=${QUEUE},name=fc_albseasonal,noask' "$WORKDIR"/stats_configfiles/fc_percentile_albers_seasonal.yaml
datacube-stats -C "$CONFIGFILE" -vvv --log-queries --qsub 'project=${PROJECT},nodes=2,ncpus=4,walltime=1h,mem=medium,queue=${QUEUE},name=fc_albannual,noask' "$WORKDIR"/stats_configfiles/fc_percentile_albers_annual.yaml
datacube-stats -C "$CONFIGFILE" -vvv --log-queries --qsub 'project=${PROJECT},nodes=2,ncpus=4,walltime=1h,mem=medium,queue=${QUEUE},name=fc_albers,noask' "$WORKDIR"/stats_configfiles/fc_percentile_albers.yaml

EOF