#!/bin/bash

set -eu

while [[ $# -gt 0 ]]; do
    key="$1"
    case ${key} in
        --deamodule )           shift
                                MODULE=$1
                                ;;
        * )                     exit 0
    esac
    shift
done

modname=$(echo "$MODULE" | sed -r "s/[/]+/_/g")
WORKDIR=/g/data/v10/work/dea_env_test/"${modname}"
SUBMISSION_LOG="$WORKDIR"/log_files/deaenv_stats-$(date '+%F-%T').log
CONFIGFILE="$(pwd)"/datacube_config.conf

# Copy yaml files from repo
sh dea_testscripts/cp_statsyaml_files.sh "$WORKDIR" "$(pwd)"

# Check if output directory exists, else create one
mkdir -p "$WORKDIR"/output_files/stats/nbar/001
mkdir -p "$WORKDIR/log_files"
echo "Start time: " "$(date '+%F-%T')" > "$SUBMISSION_LOG"

nohup "$SHELL" > "$SUBMISSION_LOG" 2>&1 << EOF &
echo "Logging results into: ${SUBMISSION_LOG}"
module use /g/data/v10/public/modules/modulefiles
module load "${MODULE}"

echo "Loading module ${MODULE}"
echo ""

# Check if we can connect to the database
datacube -C "$CONFIGFILE" system check

# Run the initialise Test Database Script
dea-system -C "$CONFIGFILE" init

# Check if we can connect to the database
datacube -vv -C "$CONFIGFILE" system check

# Redirect the PBS logs to log_files folder
cd "$WORKDIR/log_files" || exit 0

echo ""
datacube-stats -C "$CONFIGFILE" -vvv --log-queries --qsub 'project=u46,nodes=2,ncpus=4,walltime=1h,mem=medium,queue=express,name=nbar_stats,noask' "$WORKDIR"/stats_configfiles/nbar_stats.yaml
datacube-stats -C "$CONFIGFILE" -vvv --log-queries --qsub 'project=u46,nodes=2,ncpus=4,walltime=1h,mem=medium,queue=express,name=fc_stats_annual,noask' "$WORKDIR"/stats_configfiles/fc_stats_annual.yaml
datacube-stats -C "$CONFIGFILE" -vvv --log-queries --qsub 'project=u46,nodes=2,ncpus=4,walltime=1h,mem=medium,queue=express,name=fc_albseasonal,noask' "$WORKDIR"/stats_configfiles/fc_percentile_albers_seasonal.yaml
datacube-stats -C "$CONFIGFILE" -vvv --log-queries --qsub 'project=u46,nodes=2,ncpus=4,walltime=1h,mem=medium,queue=express,name=fc_albannual,noask' "$WORKDIR"/stats_configfiles/fc_percentile_albers_annual.yaml
datacube-stats -C "$CONFIGFILE" -vvv --log-queries --qsub 'project=u46,nodes=2,ncpus=4,walltime=1h,mem=medium,queue=express,name=fc_albers,noask' "$WORKDIR"/stats_configfiles/fc_percentile_albers.yaml

EOF