service: wlinsight-plot

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
  - serverless-offline
custom:
  pythonRequirements:
    dockerizePip: non-linux
  Stage: ${opt:stage, self:provider.stage}

package:
  exclude:
    - node_modules/**
    - .idea/**
    - .requirements/**
    - env/**
    - README.md
    - package.json
    - package-lock.json
    - requirements.txt

provider:
  name: aws
  runtime: python3.7
  timeout: 6  # 60 seconds. Default is 6 seconds
  memorySize: 128  # in MB, default is 1024
  region: ap-southeast-2
  stage: dev
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  iamRoleStatements:
  - Effect: "Allow"
    Resource: "*"
    Action:
      - "s3:Get*"


functions:
  wlinsight_plot:
    handler: wlinsight_plot.APP
    events:
     - http:
        path: plot/{proxy+}
        method: get
        cors: true