# Welcome to Serverless!
#
# This file is the main config file for your service.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!
service: execute-on

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

# plugins:
plugins:
  # install serverless pseudo parameters using the following:
  #   1) $ npm install serverless-pseudo-parameters --save-dev
  - serverless-pseudo-parameters

custom:
  Stage: ${opt:stage, self:provider.stage}
  profiles:
    dev: devProfile
    prod: prodProfile
  CustEnv:
    s3Bucket:
      prod: "dea-lambda"
      dev: "dea-lambdas-dev"

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 120 # 2 minutes. Default is 6 seconds
  profile: ${self:custom.profiles.${self:custom.Stage}}
  environment:
    hostkey: 'orchestrator.raijin.users.default.host'
    userkey: 'orchestrator.raijin.users.default.user'
    pkey: 'orchestrator.raijin.users.default.pkey'
    DEA_MODULE: dea/20180815
    PROJECT: v10
    QUEUE: normal
  region: ap-southeast-2
  deploymentBucket: ${self:custom.CustEnv.s3Bucket.${self:custom.Stage}}
  stackTags:
    repo: dea-orchestration
    author: nci.monitor@dea.ga.gov.au
    purpose: nci-automation
# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ssm:GetParameters'
        - 'ssm:DescribeParameters'
      Resource:
        - "arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/orchestrator.*"
        - "arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/pipeline.*"
    - Effect: 'Allow'
      Action: 'kms:Decrypt'
      Resource:
        - "arn:aws:kms:#{AWS::Region}:#{AWS::AccountId}:key/*"

functions:
  git_pull_prod:
    handler: handler.execute_ssh_command
    environment:
      hostkey: 'orchestrator.raijin.users.git_pull.host'
      userkey: 'orchestrator.raijin.users.git_pull.user'
      pkey: 'orchestrator.raijin.users.git_pull.pkey'
    events:
      - schedule:
          rate: cron(02 08 ? * THU *) # Run every Thursday, at 08:02:00 am UTC time
          enabled: false
  execute_sync:
    # trasharchived is set to 'yes' only for the albers products and not for the scenes
    handler: handler.execute_ssh_command
    environment:
      cmd: 'execute_sync --dea-module ${self:provider.environment.DEA_MODULE}
                         --queue ${self:provider.environment.QUEUE}
                         --project ${self:provider.environment.PROJECT}
                         --stage ${self:custom.Stage}
                         --year <%= year %>
                         --path <%= path %>
                         --product <%= product %>
                         --trasharchived <%= trasharchived %>'
    events:
      - schedule:
          rate: cron(10 08 ? * THU *) # Run every Thursday, at 08:10:00 am UTC time
          enabled: false
          input:
            year: 2018
            product: ls8_pq_scene
            path: '/g/data/rs0/scenes/pq-scenes-tmp/ls8/2018/'
            trasharchived: no
      - schedule:
          rate: cron(15 08 ? * THU *) # Run every Thursday, at 08:15:00 am UTC time
          enabled: false
          input:
            year: 2018
            product: ls8_level1_scene
            path: '/g/data/v10/reprocess/ls8/level1/2018/'
            trasharchived: no
      - schedule:
          rate: cron(16 08 ? * THU *) # Run every Thursday, at 08:16:00 am UTC time
          enabled: false
          input:
            year: 2018
            product: ls8_nbart_scene
            path: '/g/data/rs0/scenes/nbar-scenes-tmp/ls8/2018/01/output/nbart/'
            trasharchived: no
      - schedule:
          rate: cron(17 08 ? * THU *) # Run every Thursday, at 08:17:00 am UTC time
          enabled: false
          input:
            year: 2018
            product: ls8_nbart_scene
            path: '/g/data/rs0/scenes/nbar-scenes-tmp/ls8/2018/02/output/nbart/'
            trasharchived: no
      - schedule:
          rate: cron(18 08 ? * THU *) # Run every Thursday, at 08:18:00 am UTC time
          enabled: false
          input:
            year: 2018
            product: ls8_nbart_scene
            path: '/g/data/rs0/scenes/nbar-scenes-tmp/ls8/2018/03/output/nbart/'
            trasharchived: no
      - schedule:
          rate: cron(19 08 ? * THU *) # Run every Thursday, at 08:19:00 am UTC time
          enabled: false
          input:
            year: 2018
            product: ls8_nbart_scene
            path: '/g/data/rs0/scenes/nbar-scenes-tmp/ls8/2018/04/output/nbart/'
            trasharchived: no
      - schedule:
          rate: cron(20 08 ? * THU *) # Run every Thursday, at 08:20:00 am UTC time
          enabled: false
          input:
            year: 2018
            product: ls8_nbart_scene
            path: '/g/data/rs0/scenes/nbar-scenes-tmp/ls8/2018/05/output/nbart/'
            trasharchived: no
      - schedule:
          rate: cron(21 08 ? * THU *) # Run every Thursday, at 08:21:00 am UTC time
          enabled: false
          input:
            year: 2018
            product: ls8_nbart_scene
            path: '/g/data/rs0/scenes/nbar-scenes-tmp/ls8/2018/06/output/nbart/'
            trasharchived: no
      - schedule:
          rate: cron(22 08 ? * THU *) # Run every Thursday, at 08:22:00 am UTC time
          enabled: false
          input:
            year: 2018
            product: ls8_nbart_scene
            path: '/g/data/rs0/scenes/nbar-scenes-tmp/ls8/2018/07/output/nbart/'
            trasharchived: no
      - schedule:
          rate: cron(23 08 ? * THU *) # Run every Thursday, at 08:23:00 am UTC time
          enabled: false
          input:
            year: 2018
            product: ls8_nbart_scene
            path: '/g/data/rs0/scenes/nbar-scenes-tmp/ls8/2018/08/output/nbart/'
            trasharchived: no
      - schedule:
          rate: cron(23 08 ? * THU *) # Run every Thursday, at 08:23:00 am UTC time
          enabled: false
          input:
            year: 2018
            product: ls8_nbar_scene
            path: '/g/data/rs0/scenes/nbar-scenes-tmp/ls8/2018/01/output/nbar/'
            trasharchived: no
      - schedule:
          rate: cron(24 08 ? * THU *) # Run every Thursday, at 08:24:00 am UTC time
          enabled: false
          input:
            year: 2018
            product: ls8_nbar_scene
            path: '/g/data/rs0/scenes/nbar-scenes-tmp/ls8/2018/02/output/nbar/'
            trasharchived: no
      - schedule:
          rate: cron(25 08 ? * THU *) # Run every Thursday, at 08:25:00 am UTC time
          enabled: false
          input:
            year: 2018
            product: ls8_nbar_scene
            path: '/g/data/rs0/scenes/nbar-scenes-tmp/ls8/2018/03/output/nbar/'
            trasharchived: no
      - schedule:
          rate: cron(26 08 ? * THU *) # Run every Thursday, at 08:26:00 am UTC time
          enabled: false
          input:
            year: 2018
            product: ls8_nbar_scene
            path: '/g/data/rs0/scenes/nbar-scenes-tmp/ls8/2018/04/output/nbar/'
            trasharchived: no
      - schedule:
          rate: cron(27 08 ? * THU *) # Run every Thursday, at 08:27:00 am UTC time
          enabled: false
          input:
            year: 2018
            product: ls8_nbar_scene
            path: '/g/data/rs0/scenes/nbar-scenes-tmp/ls8/2018/05/output/nbar/'
            trasharchived: no
      - schedule:
          rate: cron(28 08 ? * THU *) # Run every Thursday, at 08:28:00 am UTC time
          enabled: false
          input:
            year: 2018
            product: ls8_nbar_scene
            path: '/g/data/rs0/scenes/nbar-scenes-tmp/ls8/2018/06/output/nbar/'
            trasharchived: no
      - schedule:
          rate: cron(29 08 ? * THU *) # Run every Thursday, at 08:29:00 am UTC time
          enabled: false
          input:
            year: 2018
            product: ls8_nbar_scene
            path: '/g/data/rs0/scenes/nbar-scenes-tmp/ls8/2018/07/output/nbar/'
            trasharchived: no
      - schedule:
          rate: cron(30 08 ? * THU *) # Run every Thursday, at 08:30:00 am UTC time
          enabled: false
          input:
            year: 2018
            product: ls8_nbar_scene
            path: '/g/data/rs0/scenes/nbar-scenes-tmp/ls8/2018/08/output/nbar/'
            trasharchived: no
      - schedule:
          rate: cron(30 08 ? * THU *) # Run every Thursday, at 08:30:00 am UTC time
          enabled: false
          input:
            year: 2018
            product: ls8_pq_legacy_scene
            path: '/g/data/rs0/scenes/pq-legacy-scenes-tmp/ls8/2018/'
            trasharchived: no
  execute_ingest:
    handler: handler.execute_ssh_command
    environment:
      cmd: 'execute_ingest --dea-module ${self:provider.environment.DEA_MODULE}
                           --queue ${self:provider.environment.QUEUE}
                           --project ${self:provider.environment.PROJECT}
                           --stage ${self:custom.Stage}
                           --year <%= year %>
                           --product <%= product %>'
    events:
      - schedule:
          rate: cron(00 17 ? * THU *) # Run every Thursday, at 17:00:00 pm UTC time
          enabled: false
          input:
            year: 2018
            product: ls8_nbart_albers
      - schedule:
          rate: cron(10 17 ? * THU *) # Run every Thursday, at 17:10:00 pm UTC time
          enabled: false
          input:
            year: 2018
            product: ls8_nbar_albers
      - schedule:
          rate: cron(45 11 ? * FRI *) # Run every Friday, at 11:45:00 am UTC time
          enabled: false
          input:
            year: 2018
            product: ls8_pq_albers
  execute_stacker:
    handler: handler.execute_ssh_command
    environment:
      cmd: 'execute_stacker --dea-module ${self:provider.environment.DEA_MODULE}
                            --queue ${self:provider.environment.QUEUE}
                            --project ${self:provider.environment.PROJECT}
                            --year <%= year %>
                            --app-config <%= appconfig %>'
    events:
      - schedule:
          rate: cron(30 04 * * ? *) # Run daily, at 04:30:00 am UTC time
          enabled: false
          input:
            year: 2018
            appconfig: ls8_nbar_albers.yaml
      - schedule:
          rate: cron(45 04 * * ? *) # Run daily, at 04:45:00 am UTC time
          enabled: false
          input:
            year: 2018
            appconfig: ls8_nbart_albers.yaml
      - schedule:
          rate: cron(00 05 * * ? *) # Run daily, at 05:00:00 am UTC time
          enabled: false
          input:
            year: 2018
            appconfig: ls8_pq_albers.yaml
  execute_fractional_cover:
    handler: handler.execute_ssh_command
    environment:
      cmd: 'execute_fractional_cover --dea-module ${self:provider.environment.DEA_MODULE}
                                     --queue ${self:provider.environment.QUEUE}
                                     --project ${self:provider.environment.PROJECT}
                                     --stage ${self:custom.Stage}
                                     --year <%= year %>
                                     --product <%= product %>
                                     --tag <%= tag %>'
    events:
      - schedule:
          rate: cron(10 08 ? * THU *) # Run every Thursday, at 08:10:00 am UTC time
          enabled: false
          input:
            year: 2018
            product: ls8_fc_albers
            tag: '2018'
  execute_wofs:
    handler: handler.execute_ssh_command
    environment:
      cmd: 'execute_wofs --dea-module ${self:provider.environment.DEA_MODULE}
                         --queue ${self:provider.environment.QUEUE}
                         --project ${self:provider.environment.PROJECT}
                         --stage ${self:custom.Stage}
                         --year <%= year %>
                         --product <%= product %>
                         --tag <%= tag %>'
    events:
      - schedule:
          rate: cron(10 10 ? * THU *) # Run every Thursday, at 10:10:00 am UTC time
          enabled: false
          input:
            year: 2018
            product: wofs_albers
            tag: '2018'
  execute_clean:
    handler: handler.execute_ssh_command
    environment:
      cmd: 'execute_clean --dea-module ${self:provider.environment.DEA_MODULE}
                          --queue ${self:provider.environment.QUEUE}
                          --project ${self:provider.environment.PROJECT}
                          --min-trash-age-hours <%= mintrashage %>
                          --search-string <%= searchstr %>'
    events:
      - schedule:
          rate: cron(00 06 * * ? *)  # Run daily, at 06:00:00 am UTC time
          enabled: false
          input:
            mintrashage: 10
            searchstr: ls8_nbar_albers
